name: Run Python Script and Update Records

on:
  watch:
    types: [started]

jobs:
  run-script-and-update:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Adjust as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Example: pip install -r requirements.txt
        # Add any necessary command to install your dependencies

    - name: Run the script
      run: python stream-data.py
      env:
        # If your script uses environment variables, set them here
        EXAMPLE_ENV_VAR: 'value'

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add patient_records.txt
        git diff --staged --quiet || git commit -m "Update patient records"
        git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/ritabanm-99/EHR-Dashboard.git
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
