name: Generate Patient Records on Star

on:
  watch:
    types: [started]

jobs:
  generate-and-append-records:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install any dependencies your script might have
        # pip install -r requirements.txt
        
    - name: Generate patient records
      run: python stream-data.py
      # Adjust the script's runtime in the script itself to limit it to a couple of minutes
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add patient_records.txt
        git diff --staged --quiet || (git commit -m "Append new patient records" && git push)
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
